### ISSUE TITLE
Error when reproduce demo on DiSECt

### ISSUE THREAD

**Issue by ANABUR920** [NVlabs/DiSECt#4]
Hi, Heiden
Thank you for sharing such awesome work of DiSECt, where the codebase is solid and cool.
But I meet some bugs when try to  **python examples/basic_cutting.py**

The following is my bug info. It seems that cannot find kernels.so
` python examples/basic_cutting.py
Rebuilding kernels
/home/anabur/anaconda3/envs/robot/lib/python3.6/site-packages/torch/utils/cpp_extension.py:298: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (clang++-9) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using clang++-9, and then you can also use
clang++-9 to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Detected CUDA files, patching ldflags
Emitting ninja build file /media/anabur/E/robot_similation/DiSECt/dflex/kernels/build.ninja...
Building extension module kernels...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
Loading extension module kernels...
Traceback (most recent call last):
  File "examples/basic_cutting.py", line 20, in <module>
    from cutting import load_settings, SlicingMotion, CuttingSim
  File "/media/anabur/E/robot_similation/DiSECt/cutting/__init__.py", line 10, in <module>
    from .cutting_sim import *
  File "/media/anabur/E/robot_similation/DiSECt/cutting/cutting_sim.py", line 25, in <module>
    from cutting.urdf_loader import load_urdf
  File "/media/anabur/E/robot_similation/DiSECt/cutting/urdf_loader.py", line 12, in <module>
    import dflex as df
  File "/media/anabur/E/robot_similation/DiSECt/dflex/__init__.py", line 15, in <module>
    kernel_init()
  File "/media/anabur/E/robot_similation/DiSECt/dflex/sim.py", line 47, in kernel_init
    kernels = df.compile()
  File "/media/anabur/E/robot_similation/DiSECt/dflex/adjoint.py", line 1934, in compile
    with_pytorch_error_handling=False)
  File "/home/anabur/anaconda3/envs/robot/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1285, in load_inline
    keep_intermediates=keep_intermediates)
  File "/home/anabur/anaconda3/envs/robot/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/anabur/anaconda3/envs/robot/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /media/anabur/E/robot_similation/DiSECt/dflex/kernels/kernels.so: cannot open shared object file: No such file or directory
`

**Comment by eric-heiden** [comment]
This looks like some pytorch issue that occurs when the C++ extension for the simulation kernels is getting compiled. Your best bet would be to ask for help on the pytorch forum, but from what I understand from the error message is the following:

Can you check that you have a new version of `g++` installed, and that it is available on your `PATH`? The error message says that you should use g++, or otherwise it may be possible to force pytorch to use Clang as C++ compiler (there is probably some help in the pytorch documentation/forum on this).

**Comment by eric-heiden** [comment]
Closing this issue for now. Feel free to reopen it if some error can be traced back to the simulation code.
